version: "3.9"

services:
  backend:
    build: ./backend
    container_name: react-backend
    ports:
      - "3176:3176"
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5176:5176"
    depends_on:
      - backend
    restart: always

 
